import { Inter } from "next/font/google";
import Sidebar from "@/components/sidebar/Sidebar";
import { GlobalStyles } from "../globalStyles";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				{children}
				<Sidebar />
			</body>
		</html>
	);
}
